POST    https://link-shortener-kappa.vercel.app//api/shortner
content-type: application/json

{
"longUrl": "https://jhely.bo/p/compra-tu-departamento-2d-con-terraza-en-equipetrol-piso-4-1a8423c0-821b-40e1-ae75-73bc559a8b6f"
}




