import axios from 'axios'
import Head from 'next/head'
import LinkShortener from '../component/LinkShortener'
export default function Home() {
  return (
    <div >
      <Head>
        <title>Shorten Link</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='grid place-items-center h-screen w-full'> 
         <LinkShortener />
      </main>
    </div>
  )
}

